apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osint-scraper-ingress
  namespace: osint
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: osint.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: osint-scraper
                port:
                  number: 80