apiVersion: v1
kind: Service
metadata:
  name: osint-scraper
  namespace: osint
  labels:
    app: osint-scraper
spec:
  selector:
    app: osint-scraper
  type: ClusterIP
  ports:
    - name: http
      port: 8080        # this is what other services use to connect
      targetPort: 8080  # this is what your container exposes
      protocol: TCP


