apiVersion: v1
kind: Service
metadata:
  name: osint-scraper
  namespace: osint
spec:
  selector:
    app: osint-scraper
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP